### PR TITLE
Dockerize and deploy

### LINKED ISSUE #8: Dockerize application
Make Dockerfile and Docker-compose example file for easier deployment.

### LINKED ISSUE #9: Deploy action to heroku
Create a workflow to deploy project to heroku.

### PR DESCRIPTION
**Pull request by triszt4n**
Closes #8 
Closes #9 

* Sets up Heroku deploy Github action: Node.js app
  * Uses the docker-compose file and Dockerfile
  * Uses secret credentials of the workflow for releasing
* The owner needs to set the MONGO_CONNECT_URL in the heroku dashboard
  * I set it to a Mongo Atlas cluster's endpoint (couldn't deploy mongodb container, see below)
* There's a docker-compose.dev.yml file for database use in dev mode
* The heroku site is available at https://unholy-oil-bunkermgr.herokuapp.com/

### CODE REVIEW

**Comment by triszt4n** [comment]
Commit 0b5951713996a4fd6e021d4d953a6b5f2e13c57e was the last idea that I wanted to try, but there were problems in the heroku dyno container...

* mongoose client cannot use 0.0.0.0 as the host of the mongodb server (ECONNREFUSED)
* mongoose client cannot use localhost as the host of the mongodb server (ECONNREFUSED)
* mongoose client cannot use docker-container name `db` as the host of the mongodb server (via docker DNS, networks)
* the port usage in heroku is strictly controlled by the dyno
* port exposing and redirecting didn't work
* used this example: https://github.com/chpmnrssll/herokuDocker but this failed as well

So in cc52c72298b9e38d970e82f17323e4948fd93ce4 I've switched to Mongo Atlas (as the Heroku addon MongoLab is no longer available, the new MongoDB addon is very pricey, so only Atlas was the best solution for this).

**Comment by triszt4n** [comment]
The sonar check failed because it ran from my fork (which does not have the SONAR_TOKEN secret)

**Review by nemaberci — APPROVED** [review]
works on my end 🗽

**Review by bbucsy — APPROVED** [review]
Nice.

**Pull request merged**
