### PR TITLE
#13 fixed eslint errors

### LINKED ISSUE #4: Static code analysis
Integrate SonarCloud to the Github repo and do a static code analysis

### LINKED ISSUE #13: Fix eslint and prettier errors
The project has a few errors/warnings. Resolve these.

### PR DESCRIPTION
**Pull request by bluebird182**

### CODE REVIEW

**Comment by gergoradeczki** [comment]
Please check why SonerCloud Code Analysis fails

**Comment by bbucsy** [comment]
Put a small configuration in  the SonarCloud config, because right now we can't provide coverage data from our tests. Should be a different issue

**Review by nemaberci — APPROVED** [review]
lgtm

**Review by triszt4n — APPROVED** [review]
Neat work ⚒️

**Pull request merged**
