### PR TITLE
Add IET-HF.md

### LINKED ISSUE #3: Write IET-HF.MD file
Write a small documentation about the project.

### PR DESCRIPTION
**Pull request by bbucsy**
Please check for grammatical errors.
closes #3

### CODE REVIEW

**Review by nemaberci — APPROVED** [review]
Looks good to me.

**Review by bluebird182 — APPROVED** [review]
Nice

**Review by triszt4n — APPROVED** [review]
Descriptive

**Comment by gergoradeczki** [comment]
Lgtm, ngl

**Review by gergoradeczki — APPROVED** [review]

**Pull request merged**
